lf:
  ros__parameters:
    "bearing_std_dev": 1e-5
    "frame_id": "base_link"
    "least_sq_angle_thresh": 1e-4
    "least_sq_radius_thresh": 1e-4
    "max_line_gap": 0.5
    "max_range": 20.0
    "min_line_length": 0.7
    "min_line_points": 9
    "min_range": 0.0508
    "min_split_dist": 0.04
    "outlier_dist": 0.06
    "publish_markers": true
    "range_std_dev": 0.012
    "scan_topic": "scan"