#! /usr/bin/bash
#ros2 bag record --compression-mode file --compression-format zstd --qos-profile-overrides-path  /home/ros/puck_ws/src/puck/puck_base/scripts/qos.yaml \
ros2 bag record --include-hidden-topics --qos-profile-overrides-path  /home/ros/raven_ws/install/raven_base/share/raven_base/scripts/qos.yaml -o ~/bag \
/bluetoothJoystick \
/clicked_point \
/cmd_vel \
/cmd_vel_joystick \
/cmd_vel_keyboard \
/cmd_vel_nav \
/global_costmap/costmap \
/goal_pose \
/initialpose \
/joint_states \
/line_markers \
/line_markers_array \
/local_costmap/costmap \
/local_costmap/published_footprint \
/local_plan \
/map \
/map_metadata \
/odom \
/odometry/filtered \
/plan \
/roboclaw_status \
/robot_description \
/scan \
/scan_left_front \
/scan_right_rear \
/sonar0Sensor \
/sonar1Sensor \
/sonar2Sensor \
/sonar3Sensor \
/t265/fisheye1/camera_info \
/t265/fisheye1/image_raw \
/teensy_diagnostics \
/teensy_stats \
/temperature \
/tf \
/tf_static \
/tof0Sensor \
/tof1Sensor \
/tof2Sensor \
/tof3Sensor \
/tof4Sensor \
/tof5Sensor \
/tof6Sensor \
/tof7Sensor \
/tofSensor \
/waypoints \
/wheel_odom
