<?xml version="1.0"?>
<!--
Copyright (c) 2023 Michael Wimble
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
-->
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="ravel">
    <xacro:include filename="$(find raven_description)/urdf/inertials.xacro" />
    <xacro:include filename="$(find raven_description)/urdf/raven_properties.urdf.xacro" />
    <xacro:include filename="$(find raven_description)/urdf/caster.urdf.xacro" />
    <xacro:include filename="$(find raven_description)/urdf/ld06.urdf.xacro" />
    <xacro:include filename="$(find raven_description)/urdf/material.urdf.xacro" />
    <xacro:include filename="$(find raven_description)/urdf/raven_gazebo.urdf.xacro" />
    <xacro:include filename="$(find raven_description)/urdf/wheel.urdf.xacro" />
    <xacro:include filename="$(find raven_description)/urdf/oakd.urdf.xacro" />


    <link name="base_link">
        <collision>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 ${(body_height/2)}" />
        </collision>
        <visual>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}" />
            </geometry>
            <material name="aluminum_frame" />
            <origin rpy="0 0 0" xyz="${(-body_length/2)+wheel_offset_from_front} 0 ${(body_height/2)}" />
        </visual>
        <inertial>
            <origin xyz="0 0 0.05" rpy="0 0 0" />
            <mass value="12" />
            <inertia ixx="${(1/12) * mass * ((body_width  * body_width)  + (body_height * body_height))}" ixy="0.0" ixz="0.0" iyy="${(1/12) * mass * ((body_length * body_length) + (body_height * body_height))}" iyz="0.0" izz="${(1/12) * mass * ((body_length * body_length) + (body_width  * body_width))}" />
        </inertial>
    </link>
    <gazebo reference="base_link">
        <material>
            aluminum_frame
        </material>
    </gazebo>

    <link name="base_footprint" />

    <!-- <link name="odom" />
    <joint name="odom_to_base_footprint_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="odom" />
        <child link="base_footprint" />
    </joint> -->

    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 ${base_to_floor_z_offset}" rpy="0 0 0" />
        <parent link="base_footprint" />
        <child link="base_link" />
    </joint>

    <xacro:wheel wheel_prefix="front_left">
        <origin xyz="0 ${(body_width/2)+wheel_center_offset} -${gear_box_center_height}" rpy="0 0 0" />
    </xacro:wheel>

    <xacro:wheel wheel_prefix="front_right">
        <origin xyz="0 -${(body_width/2)+wheel_center_offset} -${gear_box_center_height}" rpy="0 0 0" />
    </xacro:wheel>

    <xacro:caster wheel_prefix="fcaster">
        <origin xyz="${fwheel_offset} 0.0 -${wheel_radius + gear_box_center_height - caster_radius}" rpy="0 0 0" />
    </xacro:caster>
    <xacro:caster wheel_prefix="rcaster">
        <origin xyz="${-fwheel_offset} 0.0 -${wheel_radius + gear_box_center_height - caster_radius}" rpy="0 0 0" />
    </xacro:caster>

    <xacro:ld06 lidar_prefix="right_rear">
        <origin xyz="${-(body_length / 2) - 0.030}  -${((body_width / 2) - 0)} 0.200" rpy="0 0 ${M_PI}" />
    </xacro:ld06>

    <xacro:ld06 lidar_prefix="left_front">
        <origin xyz="${(body_length / 2) + 0.030}  ${((body_width / 2) - 0.0)} 0.040" rpy="0 0 0" />
    </xacro:ld06>

    <xacro:include filename="$(find raven_description)/urdf/time_of_flight.urdf.xacro" />
    <xacro:include filename="$(find raven_description)/urdf/sonar.urdf.xacro" />

    <xacro:oakd_link mount_point="right" />
    <xacro:oakd_joint mount_point="right">
        <origin xyz="0.170 -0.055 0.350" rpy="0 0 -0.523599" />
    </xacro:oakd_joint>
    <xacro:oakd_link mount_point="left" />
    <xacro:oakd_joint mount_point="left">
        <origin xyz="0.170 0.055 0.350" rpy="0 0 0.523599" />
    </xacro:oakd_joint>
</robot>