<?xml version="1.0"?>
<!--
Copyright (c) 2023 Michael Wimble
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
-->
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="ravel">
    <xacro:include filename="$(find raven_description)/urdf/caster.urdf.xacro" />
    <xacro:include filename="$(find raven_description)/urdf/ld06.urdf.xacro" />
    <xacro:include filename="$(find raven_description)/urdf/material.urdf.xacro" />
    <xacro:include filename="$(find raven_description)/urdf/raven_gazebo.urdf.xacro" />
    <xacro:include filename="$(find raven_description)/urdf/wheel.urdf.xacro" />

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="blackish">
        <color rgba="0.1 0.1 0.1 1"/>
    </material>

    <xacro:property name="M_PI" value="3.14159" />

    <xacro:property name="body_height" value="0.262" />
    <xacro:property name="body_length" value="0.4572" />
    <xacro:property name="body_width" value="0.3048" />

    <xacro:property name="caster_radius" value="0.0381" />
    <xacro:property name="caster_width" value="0.023" />
    <xacro:property name="fwheel_offset" value="0.170" />
    <xacro:property name="gear_box_center_height" value="0.015" />
    <xacro:property name="t265_height" value="0.016" />
    <xacro:property name="t265_length" value="0.100" />
    <xacro:property name="t265_width" value="0.008" />
    <xacro:property name="t265_x_offset" value="0.2126" />
    <xacro:property name="wheel_radius" value="0.10" />
    <xacro:property name="wheel_center_offset" value="0.030" />
    <xacro:property name="wheel_width" value="0.0254" />

    <xacro:property name="base_to_floor_z_offset" value="${wheel_radius+gear_box_center_height}" />
    <xacro:property name="t265_z_offset" value="${base_to_floor_z_offset+0.293}" />

    <xacro:property name="wheel_offset_from_front" value="${body_length/2}" />

    <link name="base_link">
        <collision>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 ${(body_height/2)}" />
        </collision>
        <visual>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}" />
            </geometry>
            <material name="aluminum_frame" />
            <origin rpy="0 0 0" xyz="${(-body_length/2)+wheel_offset_from_front} 0 ${(body_height/2)}" />
        </visual>
    </link>

    <link name="base_footprint" />

    <link name="odom" />
    <link name="odom_frame" />
    <joint name="odom_to_odom_frame_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />>
        <parent link="odom" />
        <child link="odom_frame" />
    </joint>
    <joint name="odom_frame_to_t265_pose_frame_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />>
        <parent link="odom_frame" />
        <child link="t265_pose_frame" />
    </joint>

    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 ${base_to_floor_z_offset}" rpy="0 0 0" />
        <parent link="base_footprint" />
        <child link="base_link" />
    </joint>

    <xacro:wheel wheel_prefix="front_left">
        <origin xyz="0 ${(body_width/2)+wheel_center_offset} -${gear_box_center_height}" rpy="0 0 0" />
    </xacro:wheel>

    <xacro:wheel wheel_prefix="front_right">
        <origin xyz="0 -${(body_width/2)+wheel_center_offset} -${gear_box_center_height}" rpy="0 0 0" />
    </xacro:wheel>

    <xacro:caster wheel_prefix="fcaster">
        <origin xyz="${fwheel_offset} 0.0 -${wheel_radius + gear_box_center_height - caster_radius}" rpy="0 0 0" />
    </xacro:caster>
    <xacro:caster wheel_prefix="rcaster">
        <origin xyz="${-fwheel_offset} 0.0 -${wheel_radius + gear_box_center_height - caster_radius}" rpy="0 0 0" />
    </xacro:caster>

    <xacro:ld06 lidar_prefix="right_rear">
        <origin xyz="${-(body_length / 2) - 0.030}  -${((body_width / 2) - 0)} 0.200" rpy="0 0 ${M_PI}"/>
    </xacro:ld06>
    
    <xacro:ld06 lidar_prefix="left_front">
        <origin xyz="${(body_length / 2) + 0.030}  ${((body_width / 2) - 0.0)} 0.040" rpy="0 0 0"/>
    </xacro:ld06>

    <!-- T265 y tilt is 31 degrees or 0.541 radians -->
    <!-- Visual odometry camera -->
    <link name="t265_pose_frame">
        <collision>
            <geometry>
                <box size="${t265_width} ${t265_length} ${t265_height}" />
                <origin xyz="0 0 0" rpy="0.0 0.0 0.0" />
            </geometry>
        </collision>
        <visual>
            <geometry>
                <box size="${t265_width} ${t265_length} ${t265_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0.0 0.0 0.0" />
            <material name="t265_material" />
        </visual>
    </link>

    <joint name="t265_to_base_footprint" type="fixed">
        <parent link="t265_rotate_frame" />
        <child link="base_footprint" />
        <origin xyz="-${t265_x_offset} 0 -${t265_z_offset}" rpy="0 0 0" />
         <!--
        <child link="base_footprint" />
        <origin xyz="-${t265_x_offset} 0 -${t265_z_offset}" rpy="0 0.541 0 " />
        -->
    </joint>

    <link name="t265_rotate_frame" />
    <joint name="t265_rotator_joint" type="fixed">
        <parent link="t265_pose_frame" />
        <child link="t265_rotate_frame" />
        <origin xyz="0 0 0" rpy="0 0.541 0" />
    </joint>

    <xacro:include filename="$(find raven_description)/urdf/time_of_flight.urdf.xacro" />
    <xacro:include filename="$(find raven_description)/urdf/sonar.urdf.xacro" />
</robot>